{"timestamp": "2025-01-03 23:56:16", "username": "System", "logger_name": "__main__", "log_level": "INFO", "message": "Starting the application."}
{"timestamp": "2025-01-03 23:56:16", "username": "System", "logger_name": "__main__", "log_level": "INFO", "message": "Table 'users' initialized successfully."}
{"timestamp": "2025-01-03 23:56:16", "username": "System", "logger_name": "__main__", "log_level": "INFO", "message": "Admin user already exists."}
{"timestamp": "2025-01-03 23:56:16", "username": "System", "logger_name": "__main__", "log_level": "INFO", "message": "Services initialized successfully."}
{"timestamp": "2025-01-03 23:56:18", "username": "v84v", "logger_name": "__main__", "log_level": "INFO", "message": "User v84v logged in."}
{"timestamp": "2025-01-03 23:56:20", "username": "v84v", "logger_name": "__main__", "log_level": "INFO", "message": "Attempting to save file: C:\\Users\\Lenovo\\OneDrive\\Documents\\GitHub\\Shiva\\logs\\20250103_235616"}
{"timestamp": "2025-01-03 23:56:21", "username": "v84v", "logger_name": "__main__", "log_level": "ERROR", "message": "An error occurred while saving the file: 'Audit_Trail'\nTraceback (most recent call last):\n  File \"C:\\Users\\Lenovo\\OneDrive\\Documents\\GitHub\\Shiva\\services\\FileManager.py\", line 138, in save_file\n    if not self.results['Audit_Trail']:\nKeyError: 'Audit_Trail'\n"}
{"timestamp": "2025-01-03 23:56:28", "username": "v84v", "logger_name": "__main__", "log_level": "INFO", "message": "Files successfully imported."}
{"timestamp": "2025-01-03 23:56:28", "username": "v84v", "logger_name": "__main__", "log_level": "INFO", "message": "File list initialized with 14 files."}
{"timestamp": "2025-01-03 23:56:28", "username": "v84v", "logger_name": "__main__", "log_level": "INFO", "message": "FileManagementDialog opened with 14 files."}
